version: '3.4'

volumes:
  tuapp-database:
    name: tuapp-database

services:
  tuapp-postgres:
    container_name: tuapp-postgres
    image: postgres:latest
    restart: always
    ports:
      - 2222:5432
    volumes:
      - tuapp-database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: tuapp
      POSTGRES_PASSWORD: tuapp