openapi: "3.0.3"
info:
  title: test-api
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /products:
    get:
      summary: Get a list of products
      responses:
        '200':
          description: Audit scores data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Add a product to the store
      requestBody:
        description: Product details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Created product
        '400':
          description: Product already exists
  /test:
    get:
      summary: Test open api
      operationId: getTest
      responses:
        '200':
          description: Test OpenApi
          content:
            application/json:
              schema:
                type: string
              example: "test is successful"
  /privet:
    get:
      summary: Вернуть приветствие
      operationId: getPrivet
      responses:
        '200':
          description: Приветствие
          content:
            text/plain:
              schema:
                type: string
              example: "привет"

components:
  schemas:
    TestObject:
      type: object
      properties:
        id:
          type: string
          format: UUID
    Error:
      type: object
      properties:
        message:
          type: string
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        name:
          type: string
        price:
          type: number
          format: double
        category:
          type: string