version: '3.4'

volumes:
  tuapp-database:
    name: tuapp-database

services:
  books-postgres:
    container_name: tuapp-postgres
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    volumes:
      - tuapp-database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: tu_user
      POSTGRES_PASSWORD: tuapp
      POSTGRES_DB: tu_db

